// спільна оболонка для всіх сторінок (хедер, футер тощо)
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header/Header";

const interFont = Inter({
  weight: ["400", "500", "600"],
  variable: "--font-family",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create TravelTrucks",
  description: "Generated by create TravelTrucks",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interFont.variable}`}>
        <Header />
        <main>{children}</main>
        <footer />
      </body>
    </html>
  );
}
